In [37]:
import pandas as pd

df = pd.read_csv('../api/data/housing_clean_2.csv')

In [38]:
df

,id,price,surface,bedrooms,restrooms,location_name,Terraza,Ascensor,Piscina,Calefacción
0,8459,630,85,3,2,A Coruña,0,0,0,0
1,8460,450,70,3,1,A Coruña,0,0,0,0
2,8461,600,90,3,2,A Coruña,0,1,0,1
3,8463,650,80,3,1,A Coruña,0,0,0,0
4,8464,650,80,3,1,A Coruña,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
93355,2576468,675,86,2,2,Zaragoza,0,1,0,0
93356,2576469,650,63,2,1,Zaragoza,0,1,0,0
93357,2576470,700,175,3,2,Zaragoza,0,0,0,1
93358,2576471,525,65,2,1,Zaragoza,0,1,0,1
93359,2576472,725,211,4,4,Zaragoza,1,0,0,0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93360 entries, 0 to 93359
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             93360 non-null  int64
 1   price          93360 non-null  int64
 2   surface        93360 non-null  int64
 3   bedrooms       93360 non-null  int64
 4   restrooms      93360 non-null  int64
 5   location_name  93360 non-null  object
 6   Terraza        93360 non-null  int64
 7   Ascensor       93360 non-null  int64
 8   Piscina        93360 non-null  int64
 9   Calefacción    93360 non-null  int64
dtypes: int64(9), object(1)
memory usage: 7.1+ MB

In [40]:
df.describe()

,id,price,surface,bedrooms,restrooms,Terraza,Ascensor,Piscina,Calefacción
count,9.336000e+04,93360.000000,93360.000000,93360.000000,93360.000000,93360.000000,93360.000000,93360.000000,93360.000000
mean,9.401239e+05,958.519955,89.556534,2.421048,1.502217,0.195266,0.622097,0.025835,0.138410
std,6.601205e+05,623.832009,40.995330,1.007071,0.636305,0.396407,0.484866,0.158645,0.345332
min,1.000000e+00,25.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.912198e+05,580.000000,64.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,6.693145e+05,780.000000,80.000000,2.000000,1.000000,0.000000,1.000000,0.000000,0.000000
75%,1.258955e+06,1125.000000,102.000000,3.000000,2.000000,0.000000,1.000000,0.000000,0.000000
max,2.576472e+06,5000.000000,300.000000,10.000000,5.000000,1.000000,1.000000,1.000000,1.000000

In [47]:
df =  df.select_dtypes(include=['number'])
df

,price,surface,bedrooms,restrooms,Terraza,Ascensor,Piscina,Calefacción
0,630,85,3,2,0,0,0,0
1,450,70,3,1,0,0,0,0
2,600,90,3,2,0,1,0,1
3,650,80,3,1,0,0,0,0
4,650,80,3,1,0,1,0,1
...,...,...,...,...,...,...,...,...
93355,675,86,2,2,0,1,0,0
93356,650,63,2,1,0,1,0,0
93357,700,175,3,2,0,0,0,1
93358,525,65,2,1,0,1,0,1
93359,725,211,4,4,1,0,0,0

In [ ]:
from sklearn.model_selection import train_test_split
features = ['surface', 'bedrooms', 'restrooms', 'Terraza', 'Ascensor', 'Piscina', 'Calefacción']
X = df[features]
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(74688, 7)
(18672, 7)
(74688,)
(18672,)

In [53]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, roc_auc_score,make_scorer

In [54]:
rf_pipe = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('rnd_forest', RandomForestRegressor())
])
rf_params = {
    "rnd_forest__n_estimators": [2, 5, 10],
    "rnd_forest__max_features": ["log2"],
    "rnd_forest__max_depth": [15, 20, 25],
    "rnd_forest__min_samples_split": [2, 3, 4, 5]
}

In [55]:
grid_search = GridSearchCV(
    estimator=rf_pipe,
    param_grid=rf_params,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    verbose=1
)

In [56]:
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)
print(grid_search.best_score_)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

KeyboardInterrupt: